Django/MyDjangoApp/MyDjangoApp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/MyDjangoApp/music/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    #views.function name
    #views.classname.as_view
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:album.id>', views.DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>[0-9]+)/$' ,views.DetailView.as_view(),name='detail' )  
]

Django/MyDjangoApp/music/models.py
from django.db import models
# from django.core.

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=191)
    album_title = models.CharField(max_length=191)
    genre = models.CharField(max_length=85)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length = 191 )
    song_title = models.CharField(max_length = 191 )
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title 
    

Django/MyDjangoApp/music/views.py
from django.views import generic
from .models import Album 
from django.views.generic.edit import CreateView , UpdateView , DeleteView


class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = "all_albums"
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    # slug_field = "detail"

Django/MyDjangoApp/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> {% block title %} Homepage {% endblock%} </title>
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel = "stylesheet" type="text/css" href = " {% static 'music/style.css' %} " />
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body class="BodyBackground">
    <nav class="nav navbar-inverse">
        <div class="container-fluid">
            <!-- logo -->
            <!-- header -->
            <div class = "nav-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="glyphicon glyphicon-menu-down"></span>
                </button>
                    <a id="brand-name" class="navbar-brand" href = "{% url 'music:index' %}"> NioSpace</a>
                </div>
                
            <!-- items in navbar -->
            <div class = "collapse navbar-collapse">
                <ul class = "nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                                Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                                Music
                        </a>
                    </li>
                    <!-- Search bar -->
                        <form action="#" method ="get" class="navbar-form navbar-left">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value="">
                
                            </div>
                        </form>
                        <!-- Right nav -->
                <ul class = "nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                              Add Song
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                        l
                        </a>
                    </li>
                </ul>
        </div>
                     
        </div>
    </nav>

{% block body%}


{% endblock%}

<script>
    var elements = document.getElementsByClassName("BodyBackground");
    // elements.style.height = screen.height;
    // elements.style.width = screen.width;
</script>

</body>
</html>

Django/MyDjangoApp/music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} {{ album.album_title }} {% endblock%}

{% block body%}

{% if error_message %}
    <p><Strong> {{ error_message }}</Strong></p>
{% endif %}


<div id ="containerSong">
    <canvas id="canvas"></canvas>
    <img  class="detail_album_logo"  src = " {{ album.album_logo }} "><br>
    <div class="musicPlayerDiv">
        <div id="SongHeading">
            <h4 id="songName">Song name : </h4>
            <h4> Album title : {{ album.album_title }} </h4>
            <h4> Artist name : {{ album.artist }}</h4>
        </div>
        <audio controls id="audioController">
        <source id ="audioPlayer" src="" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>
    </div>
</div>

<div class="songContainer">
    <div class="songList">
    {% for song in album.song_set.all %}
        <li class="song_title" onclick="setTitle('{{song.song_title}}','{{song.file_type}} ')">{{song.song_title}} </li>
    {% endfor %}
    </div>
</div>



<script type="text/javascript"> 
    var a = "{{album.album_title}}";
    var songName = document.getElementById("songName");
    var audioPLayer = document.getElementById("audioPlayer");
    var audioController = document.getElementById("audioController");
    var canvas = document.getElementById("canvas");
    var change = twoPi/objectsCount;
    var twoPi = 2*Math.PI;
    var objectsCount = 12;
    var radius = 150;

    function visulation(audio)
    {
        var context = new AudioContext();
        var src = context.createMediaElementSource(audio);
        var analyser = context.createAnalyser();
        console.log(src);
        src.connect(analyser);
        // connect this to hear audio
        analyser.connect(context.destination);
        var frequencyData = new Uint8Array(analyser.frequencyBinCount);
        var ctx = canvas.getContext("2d");
        analyser.fftSize = 256;

        var bufferLength = analyser.frequencyBinCount;
        console.log(bufferLength);
        var dataArray = new Uint8Array(bufferLength);
        canvas.width = 150;
        canvas.height = 150;
        var WIDTH = canvas.width;
        var HEIGHT = canvas.height;

        var barWidth = (WIDTH / bufferLength) * 2.5;
        var barHeight;
        var x = 0;
        var y = 0;
        // console.log(frequencyData);
    function renderFrame() {
      requestAnimationFrame(renderFrame);
      x = 0;
      y = 0;
      analyser.getByteFrequencyData(dataArray);

      ctx.fillStyle = "#000";
      ctx.fillRect(0, 0, WIDTH, HEIGHT);

      for (var i = 0; i < bufferLength; i++) {
        barHeight = dataArray[i];
        var r = barHeight + (25 * (i/bufferLength));
        var g = 256 * (i%bufferLength);
        var b = 50 ;
        ctx.fillStyle = "rgb(" + r + "," + g + "," + b + ")";
        ctx.fillRect(x, HEIGHT - barHeight, barWidth, barHeight);
        x += barWidth + 1;
      }
    } 
    audio.play();
    renderFrame();
    }
    function setTitle(title,titleSrc){
        console.log(titleSrc);
        songName.innerHTML = "Song name : "+title;
        audioPLayer.src = "{{link.url}}/"+titleSrc;
        audioController.load();
        // audioController.play();
        visulation(audioController);      
    }

 </script>


{% endblock%} 

Django/MyDjangoApp/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block title %} index {% endblock%}
{% block body%}

{% if all_albums %}

{% for album in all_albums %}
    <div class="CardAlbum" >
        <a id="album_title" href = "{% url 'music:detail' album.id %}">
        <img class="index_album_logo" src="{{ album.album_logo }}" alt="Avatar" >
        </a>
        <div class="AlbumContainer">
            <h6><b> Artist : {{album.artist}}</b></h6>
            <h6><b> Album : {{ album.album_title }}</b></h6> 
        </div>
    </div> 


{% endfor %} 

{% else %}
        <h3>Currenlly there are no album </h3>
{% endif %}



<style>
*{
    box-sizing: border-box;
}
     
</style>

<script>
    
// Get the elements with class="column"
var elements = document.getElementsByClassName("CardAlbum");
// Declare a loop variable
var i;

for (i = 0; i < elements.length; i++) {
    elements[i].style.backgroundImage = "url( {{album.album_logo}} )";
}
        
</script>

{% endblock%}